### ISSUE TITLE
Run tests on PR

### ISSUE THREAD

**Issue by lexfrei** [BlueMonday/go-scryfall#17]
Hi!
Do you need any help with ci/cd?
As you can see in #15, someone (ex.: me) can miss tests or else. Such PRs have to be blocked automatically to save your time.
It's easy to do some checks with Travis, GH Actions or something else.
Feel free to ask me for any help you need.

**Comment by BlueMonday** [comment]
I think travis should run the tests and block the pull request if it fails?

https://github.com/BlueMonday/go-scryfall/blob/master/.travis.yml#L10

**Comment by lexfrei** [comment]
Look at #15, it wasn't blocked by Travis (or coveralls) at 622908f, but tests were broken.
I can implement this for you if you need.

**Comment by BlueMonday** [comment]
Finally got around to fixing this, thanks for reporting it!

After making some changes, Github blocked this pull request from being merging: https://github.com/BlueMonday/go-scryfall/pull/18

I had to migrate from travis-ci.org to travis-ci.com and start using the Github Travis App instead of using web hooks in order to enable mandatory checks.
